backendBaseUrl=http://127.0.0.1:8000
#backendBaseUrl=http://host.docker.internal:8000

backendTimeoutMs=2000

serverIdByGamePort.7001=server1
serverIdByGamePort.7002=server2
serverIdByGamePort.7003=server3

listenerHost.server1=visible-serving.gl.at.ply.gg
listenerPort.server1=21914

listenerHost.server2=southern-replication.gl.at.ply.gg
listenerPort.server2=21918

listenerHost.server3=library-jonathan.gl.at.ply.gg
listenerPort.server3=23392

payloadHmacSecret=change-me
universeDir=universe

